export default [
  {
    id: "1",
    title: "How to Make Someone Love You Forever! In 90 Minutes or Less",
    subTitle: "",
    authors: ["Nicholas Boothman"],
    publishedDate: "May 1, 2004",
    averageRating: "4.5",
    previewLink:
      "https://openlibrary.org/books/OL8015118M/How_to_Make_Someone_Love_You_Forever%21_In_90_Minutes_or_Less",
  },
  {
    id: "2",
    title: "Charlotte's Web",
    subTitle: "",
    authors: ["E.B.White"],
    publishedDate: "October 15, 1952",
    averageRating: "4.0",
    previewLink: "https://openlibrary.org/works/OL483391W/Charlotte%27s_Web",
  },
  {
    id: "3",
    title: "The dreamsnatcher",
    subTitle: "",
    authors: ["Abi Elphinstone"],
    publishedDate: "26 February, 2015",
    averageRating: "4.0",
    previewLink: "https://openlibrary.org/works/OL21485703W/The_dreamsnatcher",
  },
  {
    id: "4",
    title: "Scott Pilgrim (Comic Series)",
    subTitle: "",
    authors: ["Bryan Lee O'Malley"],
    publishedDate: "14 August, 2004",
    averageRating: "4.8",
    previewLink:
      "https://archive.org/details/6-scott-pilgrim/1%23%20Scott%20Pilgrim%27s%20Precious%20Little%20Life/page/181/mode/2up",
  },
  {
    id: "5",
    title: "Vedic Mathematics",
    subTitle: "",
    authors: ["Bharati Krishna Tirth Ji Maharaj"],
    publishedDate: "1 December, 1985",
    averageRating: "5.0",
    previewLink:
      "https://archive.org/details/vedic-mathematics-bharati-krishna-tirth-ji-maharaj",
  },
  {
    id: "6",
    title: "Eat that frog!",
    subTitle: "",
    authors: ["Brian Tracy"],
    publishedDate: "2001",
    averageRating: "3.9",
    previewLink:
      "https://openlibrary.org/works/OL2392324W/Eat_That_Frog%21_21_Great_Ways_to_Stop_Procrastinating_and_Get_More_Done_in_Less_Time",
  },
  {
    id: "7",
    title: "Earth abides",
    subTitle: "",
    authors: ["George Rippey Stewart"],
    publishedDate: "January 1, 1949",
    averageRating: "3.9",
    previewLink: "https://openlibrary.org/works/OL2321336W/Earth_abides",
  },
  {
    id: "8",
    title: "Fear no evil",
    subTitle: "",
    authors: ["Anatoly Shcharansky"],
    publishedDate: "January 1, 1988",
    averageRating: "4.4",
    previewLink: "https://openlibrary.org/books/OL2407753M/Fear_no_evil",
  },
  {
    id: "9",
    title: "History of My Life",
    subTitle: "",
    authors: ["Giacomo Casanova"],
    publishedDate: "February 6, 2007",
    averageRating: "3.3",
    previewLink: "https://openlibrary.org/works/OL1156251W/M%C3%A9moires",
  },
  {
    id: "10",
    title: "The Psychology of Money",
    subTitle: "",
    authors: ["Morgan Housel"],
    publishedDate: "Sep 08, 2020",
    averageRating: "4.0",
    previewLink:
      "https://openlibrary.org/works/OL21640039W/The_Psychology_of_Money#starRatingSection",
  },
];
