export default [
  {
    id: "1",
    title: "How to Make Someone Love You Forever! In 90 Minutes or Less",
    subTitle: "",
    authors: ["Nicholas Boothman"],
    publishedDate: "May 1, 2004",
    averageRating: "4.5",
    previewLink:
      "https://openlibrary.org/books/OL8015118M/How_to_Make_Someone_Love_You_Forever%21_In_90_Minutes_or_Less",
    thumnail: "https://covers.openlibrary.org/b/id/507710-L.jpg",
  },
  {
    id: "2",
    title: "Charlotte's Web",
    subTitle: "",
    authors: ["E.B.White"],
    publishedDate: "October 15, 1952",
    averageRating: "4.0",
    previewLink: "https://openlibrary.org/works/OL483391W/Charlotte%27s_Web",
    thumnail: "https://covers.openlibrary.org/b/id/14647341-L.jpg",
  },
  {
    id: "3",
    title: "The dreamsnatcher",
    subTitle: "",
    authors: ["Abi Elphinstone"],
    publishedDate: "26 February, 2015",
    averageRating: "4.0",
    previewLink: "https://openlibrary.org/works/OL21485703W/The_dreamsnatcher",
    thumnail: "https://covers.openlibrary.org/b/id/10375263-L.jpg",
  },
  {
    id: "4",
    title: "Scott Pilgrim (Comic Series)",
    subTitle: "",
    authors: ["Bryan Lee O'Malley"],
    publishedDate: "14 August, 2004",
    averageRating: "4.8",
    previewLink:"https://archive.org/details/6-scott-pilgrim/1%23%20Scott%20Pilgrim%27s%20Precious%20Little%20Life/page/181/mode/2up",
    thumnail:"https://ia800504.us.archive.org/BookReader/BookReaderImages.php?zip=/11/items/6-scott-pilgrim/1%23%20Scott%20Pilgrim%27s%20Precious%20Little%20Life_jp2.zip&file=1%23%20Scott%20Pilgrim%27s%20Precious%20Little%20Life_jp2/1%23%20Scott%20Pilgrim%27s%20Precious%20Little%20Life_0000.jp2&id=6-scott-pilgrim&scale=8&rotate=0",
  },
  {
    id: "5",
    title: "Vedic Mathematics",
    subTitle: "",
    authors: ["Bharati Krishna Tirth Ji Maharaj"],
    publishedDate: "1 December, 1985",
    averageRating: "5.0",
    previewLink:
      "https://archive.org/details/vedic-mathematics-bharati-krishna-tirth-ji-maharaj",
    thumnail:
      "https://ia801809.us.archive.org/BookReader/BookReaderImages.php?zip=/11/items/vedic-mathematics-bharati-krishna-tirth-ji-maharaj/Vedic%20Mathematics%20-%20Bharati%20Krishna%20Tirth%20Ji%20Maharaj_jp2.zip&file=Vedic%20Mathematics%20-%20Bharati%20Krishna%20Tirth%20Ji%20Maharaj_jp2/Vedic%20Mathematics%20-%20Bharati%20Krishna%20Tirth%20Ji%20Maharaj_0000.jp2&id=vedic-mathematics-bharati-krishna-tirth-ji-maharaj&scale=4&rotate=0",
  },
  {
    id: "6",
    title: "Eat that frog!",
    subTitle: "",
    authors: ["Brian Tracy"],
    publishedDate: "2001",
    averageRating: "3.9",
    previewLink:
      "https://openlibrary.org/works/OL2392324W/Eat_That_Frog%21_21_Great_Ways_to_Stop_Procrastinating_and_Get_More_Done_in_Less_Time",
    thumnail: "https://covers.openlibrary.org/b/id/14822001-L.jpg",
  },
  {
    id: "7",
    title: "Earth abides",
    subTitle: "",
    authors: ["George Rippey Stewart"],
    publishedDate: "January 1, 1949",
    averageRating: "3.9",
    previewLink: "https://openlibrary.org/works/OL2321336W/Earth_abides",
    thumnail: "https://covers.openlibrary.org/b/id/7394802-L.jpg",
  },
  {
    id: "8",
    title: "Fear no evil",
    subTitle: "",
    authors: ["Anatoly Shcharansky"],
    publishedDate: "January 1, 1988",
    averageRating: "4.4",
    previewLink: "https://openlibrary.org/books/OL2407753M/Fear_no_evil",
    thumnail: "https://covers.openlibrary.org/b/id/14809759-L.jpg",
  },
  {
    id: "9",
    title: "History of My Life",
    subTitle: "",
    authors: ["Giacomo Casanova"],
    publishedDate: "February 6, 2007",
    averageRating: "3.3",
    previewLink: "https://openlibrary.org/works/OL1156251W/M%C3%A9moires",
    thumnail: "https://covers.openlibrary.org/b/id/12997475-L.jpg",
  },
  {
    id: "10",
    title: "The Psychology of Money",
    subTitle: "",
    authors: ["Morgan Housel"],
    publishedDate: "Sep 08, 2020",
    averageRating: "4.0",
    previewLink:"https://openlibrary.org/works/OL21640039W/The_Psychology_of_Money#starRatingSection",
    thumnail: "https://covers.openlibrary.org/b/id/14820511-L.jpg",
  },
  {
    id: "11",
    title: "5 point Someone",
    subTitle: "",
    authors: ["Chetan Bhagat"],
    publishedDate: "May 01, 2004",
    averageRating: "4.4",
    previewLink:
      "https://www.goodreads.com/book/show/105576.Five_Point_Someone",
    thumnail: "https://covers.openlibrary.org/b/id/14820511-L.jpg",
  },
  {
    id: "12",
    title: "How to talk with Sora",
    subTitle: "",
    authors: ["Prem"],
    publishedDate: "October 2023",
    averageRating: "10.0",
    previewLink:
      "https://www.goodreads.com/book/show/105576.Five_Point_Someone",
    thumnail: "https://covers.openlibrary.org/b/id/14820511-L.jpg",
  },
  {
    id: "13",
    title: "How not to talk with Batsman",
    subTitle: "",
    authors: ["Bhasker"],
    publishedDate: "April 2024",
    averageRating: "00.1",
    previewLink:
      "https://www.goodreads.com/book/show/105576.Five_Point_Someone",
    thumnail: "https://covers.openlibrary.org/b/id/14820511-L.jpg",
  },
  {
    id: "14",
    title: "Billionaires ?",
    subTitle: "",
    authors: ["Aniket"],
    publishedDate: "April 2024",
    averageRating: "06.00",
    previewLink:
      "https://www.goodreads.com/book/show/105576.Five_Point_Someone",
    thumnail: "https://covers.openlibrary.org/b/id/14820511-L.jpg",
  },
  {
    id: "15",
    title: "The Shadow of the Wind",
    subTitle: "",
    authors: ["Carlos Ruiz Zafón"],
    publishedDate: "January 2001",
    averageRating: "04.30",
    previewLink:
      "https://www.goodreads.com/book/show/1232.The_Shadow_of_the_Wind?from_search=true&from_srp=true&qid=MHuZkbIzXe&rank=1",
    thumnail: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1628791882i/1232.jpg",
  },
  {
    id: "16",
    title: "Tudo é Rio",
    subTitle: "",
    authors: ["Carla Madeira"],
    publishedDate: "January 2014",
    averageRating: "04.25",
    previewLink:
      "https://www.goodreads.com/book/show/41734693-tudo-rio?from_search=true&from_srp=true&qid=NY4szTCt9Y&rank=1",
    thumnail: "https://img.travessa.com.br/livro/GR/7c/7c915f39-5306-4382-aae8-5750af26951c.jpg",
  },
  {
    id: "17",
    title: "You Had Me At Hello",
    subTitle: "",
    authors: ["Mhairi McFarlane"],
    publishedDate: "November 2012",
    averageRating: "03.79",
    previewLink:
      "https://www.goodreads.com/book/show/15733851-you-had-me-at-hello?from_search=true&from_srp=true&qid=CtiH9qORjF&rank=1",
    thumnail: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348787624i/15733851.jpg",
  },
];
